FROM node:20.8.1-slim

# create an app directory
WORKDIR /app

# install app dependecies
COPY package*.json ./

# install dependencies
RUN npm install --force

# copy app source code
COPY ./src .

EXPOSE 3000

CMD ["npm", "start"]